// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj8PwjlgfBepJsqVz2JkbKuvLMOBYxtxg',
    appId: '1:936084751914:web:b5897998648a75267aa553',
    messagingSenderId: '936084751914',
    projectId: 'uninest-backend',
    authDomain: 'uninest-backend.firebaseapp.com',
    storageBucket: 'uninest-backend.firebasestorage.app',
    measurementId: 'G-FM445B1PXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAalWscQ83QVwMCnVT4A304i7Y0SkpBago',
    appId: '1:936084751914:android:c6470175f2c5b81d7aa553',
    messagingSenderId: '936084751914',
    projectId: 'uninest-backend',
    storageBucket: 'uninest-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwP_ZDMQQMtCzw4VKtFFJfWPRm5ygHTBs',
    appId: '1:936084751914:ios:186f022a682867e37aa553',
    messagingSenderId: '936084751914',
    projectId: 'uninest-backend',
    storageBucket: 'uninest-backend.firebasestorage.app',
    iosBundleId: 'com.example.uniNestVendor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwP_ZDMQQMtCzw4VKtFFJfWPRm5ygHTBs',
    appId: '1:936084751914:ios:186f022a682867e37aa553',
    messagingSenderId: '936084751914',
    projectId: 'uninest-backend',
    storageBucket: 'uninest-backend.firebasestorage.app',
    iosBundleId: 'com.example.uniNestVendor',
  );
}
